### PR TITLE
Wait for ipv4 enhancement

### PR DESCRIPTION
**Pull request by juanxhos**

### CODE REVIEW

**Comment by tyler-ball** [comment]
This LGTM. Have you tested it locally?

**Review by usepowershell — COMMENTED** [review]
LGTM as well - just have a couple of style errors to clean up.

**Comment by jjasghar** [comment]
I'll test this too, today.

**Comment by jjasghar** [comment]
@jcalonsoh if you can fix [this error](https://travis-ci.org/chef-partners/chef-provisioning-vsphere/builds/225676295#L286) and put in a skip for the other one this should be good to go. 

If you could also add a unit test that would be ⭐️  but if you don't know how that's ok for the time being. (I have a plan of revisiting testing across the board here for this gem, I just haven't got to it yet)

**Comment by juanxhos** [comment]
It's mandatory style 599 ?

**Comment by juanxhos** [comment]
@tyler-ball LGTM there is no Board with feature set ?

**Comment by jjasghar** [comment]
> It's mandatory style 599 ?
 
As of right now no, that's why you can add the `rubocop disable` if you want. There are enough nonstandard things going on here, that I'm ok with not mandating anything _yet_.

**Comment by juanxhos** [comment]
ok, I am almost finish testing at my infra....

**Comment by juanxhos** [comment]
Fiu, all looks good https://gist.github.com/jcalonsoh/6cca538ebe74706d1f9a17251a23ad27 so infra its pool resource with an very old hardware with HDD

**Comment by jjasghar** [comment]
Amazing! Thank you.

I'll be merging and releasing this tomorrow.

💯  🏅 🥇

**Comment by juanxhos** [comment]
I also found an issue on static ip an delay https://gist.github.com/jcalonsoh/e97320a6a14bd3c1352dafdf1175e67c

**Comment by jjasghar** [comment]
@jcalonsoh want me to hold off merging this? So you can fix the static ip issue?

**Comment by juanxhos** [comment]
mmm, I'm working on it actually, @jjasghar ... so yes

**Comment by juanxhos** [comment]
@jjasghar finally... I think It can be merged https://gist.github.com/jcalonsoh/8295cfeeb9504bf50a97387579267c2e

**Comment by juanxhos** [comment]
@jjasghar 100% sure for merge
https://gist.github.com/jcalonsoh/16c05f9a5715c084cc3c910bb04e5d7b

All scenarios tested with, without custom spec.. static and dhcpd ip

**Pull request merged**
