### PR TITLE
Handle IPv6 address returned by VM

### PR DESCRIPTION
**Pull request by jzinn**
### Description

Prevents this error message when running `kitchen create`:

    ------Exception-------
    Class: Kitchen::ActionFailed
    Message: 1 actions failed.
        Failed to complete #create action: [bad URI(is not URI?): http://caec:cec6:c4ef:bb7b:1a78:d055:216d:3a78:5985/wsman] on the-vm-name
    ----------------------
    Please see .kitchen/logs/kitchen.log for more details
    Also try running `kitchen diagnose --all` for configuration

The URI

    http://caec:cec6:c4ef:bb7b:1a78:d055:216d:3a78:5985/wsman

should have brackets around the IPv6 address, like this:

    http://[caec:cec6:c4ef:bb7b:1a78:d055:216d:3a78]:5985/wsman

### Issues Resolved

https://github.com/chef-partners/chef-provisioning-vsphere/issues/52

### Check List

- [x] All tests pass.
- [x] All style checks pass.
- [ ] Functionality includes testing.

    Raising an exception where the modification is causes no tests to fail, so I could not find a convenient place to add a new test.  Sorry.

- [x] Functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by jjasghar** [comment]
Oh rock on thanks! Can you add to the reader also about this change? :metal:

**Comment by jzinn** [comment]
What is the reader?

**Comment by jjasghar** [comment]
Sorry autocorrect on my phone, the README.md file. We need documentation to show we support IPv6 with this merge.

**Comment by jzinn** [comment]
I updated the README.

**Pull request merged**
